# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_LXB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'YYModel'
  pod 'DZNEmptyDataSet'
  pod 'SDCycleScrollView', '~> 1.65'
  pod 'Reachability'
  pod 'MMPopupView'
  pod 'MBProgressHUD','~>0.8'
  pod 'IQKeyboardManager'
  pod 'YYText'

  # Pods for iOS_LXB

  target 'iOS_LXBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_LXBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
